name: seg_edit_dist_0.2_edit_dist_0.2
pipeline:
  - tag: audio_lang
    ref_value: en
  - tag: text_lang
    ref_value: en
  - tag: edit_dist
    upper_bound: 0.2
    inclusive: true
  - tag: seg_edit_dist
    upper_bound: 0.2
    inclusive: true