# base image - pytorch
FROM pytorch/pytorch:2.4.0-cuda11.8-cudnn9-runtime

# setting the environment variables
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# creating a directory for the project
WORKDIR /stage/

# copying requirements file
COPY requirements-main.txt requirements-main.txt

# installing dependencies
RUN pip install -r requirements-main.txt

# copying necessary files and directories to container
COPY open_whisper open_whisper/
