FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

# Setting environment variables
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=$CUDA_HOME/bin:$PATH
ENV LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

# Set working directory for the project
WORKDIR /stage/

# Install necessary system packages and AWS CLI
RUN apt-get update && apt-get install -y \
    git \
    wget \
    unzip \
    curl \
    build-essential \
    python3-dev

# Install fastText
RUN wget https://github.com/facebookresearch/fastText/archive/v0.9.2.zip && \
    unzip v0.9.2.zip && \
    cd fastText-0.9.2 && \
    make && \
    pip install .
